{"query":"\n          query GithubBranchCommits($repositoryUrl: String!, $branch: String!) {\n            github {\n              commits(repositoryUrl: $repositoryUrl, branch: $branch) {\n                sha\n                message\n                author\n                committer\n              }\n            }\n          }\n        ","variables":{"repositoryUrl":"https://github.com/tjsharp1/engi-blockchain-gql","branch":"solve-engineer-job"}}
